# Generated by Django 4.1.2 on 2023-03-11 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitut', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogposts',
            old_name='name',
            new_name='title',
        ),
    ]
